### PR TITLE
docs: Improve comment wording

### PR DESCRIPTION
**Pull request by lumynou5**
# Description

Improve comment wording.

Discussion needed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lumynou5** [comment]
Suggestion:
- Correcting abbreviations to uppercases. e.g.: "ID" istead of "id".

**Review by SiongSng — DISMISSED** [review]
LGTM

**Comment by SiongSng** [comment]
> Suggestion:
> 
>     * Correcting abbreviations to uppercases. e.g.: "ID" istead of "id".

@Luminous-Coder 如果是註解這樣做應該會好一點，但變數的話應該是不用改

**Comment by lumynou5** [comment]
> > Suggestion:
> > ```
> > * Correcting abbreviations to uppercases. e.g.: "ID" istead of "id".
> > ```
> 
> @Luminous-Coder 如果是註解這樣做應該會好一點，但變數的話應該是不用改

這個 PR 只針對註解。

**Comment by SiongSng** [comment]
> > > Suggestion:
> > > ```
> > > * Correcting abbreviations to uppercases. e.g.: "ID" istead of "id".
> > > ```
> > 
> > @Luminous-Coder 如果是註解這樣做應該會好一點，但變數的話應該是不用改
> 
> 這個 PR 只針對註解。

Ok

**Review by banahaker — COMMENTED** [review]
Cool

**Review by SiongSng — DISMISSED** [review]

**Comment by lumynou5** [comment]
Is [8379c5f](https://github.com/Lipoic/Lipoic-Backend/pull/22/commits/8379c5f581c25d30efd1ec21366284f5a5720b8e) ok?

**Comment by lumynou5** [comment]
檢查一下有沒有哪裡漏掉什麼的

**Review by SiongSng — APPROVED** [review]
LGTM

**Pull request merged**
