### PR TITLE
refactor!: rename route from `classroom` to `class`

### PR DESCRIPTION
**Pull request by SiongSng**
# Description
把 `classroom` 相關的內容都改為 `class`，更貼近班級的英文翻譯。

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by lumynou5 — COMMENTED** [review]
`instance` is not a good name. Reserve before a better name was found.

**Comment by SiongSng** [comment]
> `instance` is not a good name. Reserve before a better name was found.

How about `document`?

**Comment by HACO8888** [comment]
How about just call `NewClass`

**Comment by lumynou5** [comment]
BTW, add an exclamation mark.
Haven't you read the guideline I wrote in Discord?

**Review by lumynou5 — APPROVED** [review]

**Comment by SiongSng** [comment]
ready for merge?

**Pull request merged**
